# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160830_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='commune',
        ),
        migrations.RemoveField(
            model_name='project',
            name='contexte_commune',
        ),
        migrations.RemoveField(
            model_name='project',
            name='departement',
        ),
        migrations.RemoveField(
            model_name='project',
            name='label_ecoquartier',
        ),
        migrations.RemoveField(
            model_name='project',
            name='procedure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='region',
        ),
        migrations.RemoveField(
            model_name='project',
            name='statut',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type_operation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='vocation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='zonage_insee',
        ),
    ]
