# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160830_1049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='commune_link',
            new_name='commune',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='contexte_commune_link',
            new_name='contexte_commune',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='departement_link',
            new_name='departement',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='label_ecoquartier_link',
            new_name='label_ecoquartier',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='procedure_link',
            new_name='procedure',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='region_link',
            new_name='region',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='statut_link',
            new_name='statut',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='type_operation_link',
            new_name='type_operation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='vocation_link',
            new_name='vocation',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='zonage_insee_link',
            new_name='zonage_insee',
        ),
    ]
