# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 11:00
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160830_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='coordonnees_geogrpahiques_gis',
            field=django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326),
        ),
    ]
