# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160830_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='coordonnees_geographiques',
        ),
    ]
