# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 15:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_remove_project_coordonnees_geographiques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='coordonnees_geogrpahiques_gis',
            new_name='coordonnees_geographiques',
        ),
    ]
