# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-13 19:09
from __future__ import unicode_literals

from django.db import migrations


def change_non_to_autre(apps, schema_editor):
    LabelEcoQuartier = apps.get_model("projects", "LabelEcoQuartier")
    label = LabelEcoQuartier.objects.get(label='NON')
    label.label = "Autre"
    label.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20160830_1558'),
    ]

    operations = [
    	migrations.RunPython(change_non_to_autre, reverse_func),
    ]
