# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160913_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.TextField()),
                ('ancienne_region', models.TextField()),
                ('n_dept', models.TextField()),
                ('nom_dept', models.TextField()),
                ('code_insee', models.TextField()),
                ('ville', models.TextField()),
                ('nom_ecoquartier', models.TextField()),
                ('population', models.TextField()),
                ('commune_rurale_ou_urbaine', models.TextField()),
                ('situation_territoriale', models.TextField()),
                ('situation_du_quartier', models.TextField()),
                ('type_d_operation', models.TextField()),
                ('nombre_d_habitants_dans_le_quartier', models.TextField()),
                ('nombre_de_logements', models.TextField()),
                ('nombre_de_logements_sociaux', models.TextField()),
                ('superficie_du_quartier_ha', models.TextField()),
                ('epa', models.TextField()),
                ('anru', models.TextField()),
                ('pnr', models.TextField()),
                ('aap_2009', models.TextField()),
                ('aap_2011', models.TextField()),
                ('charte', models.TextField()),
                ('candidat_2013', models.TextField()),
                ('resultats_2013', models.TextField()),
                ('candidat_2014', models.TextField()),
                ('resultats_2014', models.TextField()),
                ('candidat_2015', models.TextField()),
                ('resultats_2015', models.TextField()),
                ('dotation_evaluation', models.TextField()),
                ('commentaires', models.TextField()),
                ('candidat_potentiel_reperage_ad4_2017', models.TextField()),
                ('candidat_2016', models.TextField()),
                ('avancement_dans_la_demarche', models.TextField()),
                ('contact_1_mail', models.TextField()),
                ('contact_1_titre', models.TextField()),
                ('contact_1_prenom_nom', models.TextField()),
                ('contact_2_mail', models.TextField()),
                ('contact_2_titre', models.TextField()),
                ('contact_2_prenom_nom', models.TextField()),
                ('contact_3_mail', models.TextField()),
                ('contact_3_titre', models.TextField()),
                ('contact_3_prenom_nom', models.TextField()),
                ('contact_4_mai', models.TextField()),
                ('contact_4_titre', models.TextField()),
                ('contact_4_prenom_nom', models.TextField()),
                ('contact_5_mail', models.TextField()),
                ('contact_5_titre', models.TextField()),
                ('contact_5_prenom_nom', models.TextField()),
                ('contact_6_mail', models.TextField()),
                ('contact_6_titre', models.TextField()),
                ('contact_6_prenom_nom', models.TextField()),
                ('contact_7_mail', models.TextField()),
                ('contact_7_titre', models.TextField()),
                ('contact_7_prenom_nom', models.TextField()),
            ],
        ),
    ]
