# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20160921_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='code_insee',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
