# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:15
from __future__ import unicode_literals

from django.db import migrations


def update_code_insee(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        commune = project.commune
        commune.code_insee = project.code_insee
        commune.save()


def reverse_func(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        commune = project.commune
        commune.code_insee = "0"
        commune.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_commune_code_insee'),
    ]

    operations = [
        migrations.RunPython(update_code_insee, reverse_func),
    ]
