# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_auto_20160921_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code_insee',
        ),
    ]
