# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_charte_commune'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='code_insee',
            field=models.CharField(max_length=255),
        ),
    ]
