# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 15:21
from __future__ import unicode_literals

from django.db import migrations


def update_commune_charte(apps, schema_editor):
    Charte = apps.get_model("projects", "Charte")
    Commune = apps.get_model("projects", "Commune")
    chartes = Charte.objects.exclude(code_insee='')
    for charte in chartes:
        commune, created = Commune.objects.get_or_create(code_insee=charte.code_insee, defaults={'label':charte.ville})
        charte.commune = commune
        charte.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20160921_1539'),
    ]

    operations = [
        migrations.RunPython(update_commune_charte, reverse_func),
    ]
