# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-21 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160921_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='charte_ecoquartier',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
