# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-27 19:57
from __future__ import unicode_literals

import glob
import shutil
import os
from PIL import Image

from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.db import migrations
from django.template.defaultfilters import slugify


dir_path = os.path.dirname(os.path.realpath(__file__))


def import_photo(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ProjectPhoto = apps.get_model("projects", "ProjectPhoto")
    path = os.path.join(dir_path, 'data', 'project-files')
    projects = Project.objects.all()
    folders = os.walk(path).next()[1]
    img_dict = {}
    for folder in folders:
        img_files = []
        folder_path = os.path.join(path, folder)
        project_name = folder.split('_')[0]
        for root, subdirs, files in os.walk(folder_path):
            for file in files:
                if os.path.splitext(file)[1].lower() in ('.jpg', '.jpeg', '.png'):
                    img_files.append(os.path.join(root, file))
                    img_dict[slugify(project_name)] = img_files
    keys = img_dict.keys()
    for project in projects:
        if slugify(project.nom) in keys:
            images = img_dict[slugify(project.nom)]
            for order, image in enumerate(images):
                project_photo = ProjectPhoto(project=project, order=order+1, title=os.path.basename(image))
                image_rel_path = image.replace('/src/projects/migrations/data/project-files/', '')
                project_photo.photo = image_rel_path
                image_new_path = image.replace('/src/projects/migrations/data/project-files', '/var/www/media')
                try:
                    os.makedirs(os.path.dirname(image_new_path))
                except:
                    pass
                shutil.copy(image, image_new_path)
                project_photo.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_projectphoto'),
    ]

    operations = [
        migrations.RunPython(import_photo, reverse_func),
    ]
