# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0023_auto_20160927_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='commune',
            name='departement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Departement'),
        ),
        migrations.AddField(
            model_name='departement',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Region'),
        ),
    ]
