# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 16:18
from __future__ import unicode_literals

from django.db import migrations


def rebuild_commune_departement_region(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Region = apps.get_model("projects", "Region")
    Departement = apps.get_model("projects", "Departement")
    Commune = apps.get_model("projects", "Commune")
    projects = Project.objects.all()
    for project in projects:
        commune = project.commune
        departement = project.departement
        region = project.region
        commune.departement = departement
        commune.save()
        departement.region = region
        departement.save()


def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_auto_20161003_1617'),
    ]

    operations = [
        migrations.RunPython(rebuild_commune_departement_region, reverse_func),
    ]
