# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_auto_20161003_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
