# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 19:13
from __future__ import unicode_literals

import datetime

from django.db import migrations


def change_date_format(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        project.mise_a_jour = datetime.datetime.strptime(project.mise_a_jour, '%d/%m/%Y').strftime('%Y-%m-%d')
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_auto_20161003_1859'),
    ]

    operations = [
        migrations.RunPython(change_date_format, reverse_func),
    ]
