# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_auto_20161003_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mise_a_jour',
            field=models.DateField(),
        ),
    ]
