# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:19
from __future__ import unicode_literals

from django.db import migrations


def change_bool(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.littorale == 'NON':
            project.littorale = 0
        elif project.littorale == 'OUI':
            project.littorale = 1
        if project.montagne == 'NON':
            project.montagne = 0
        elif project.montagne == 'OUI':
            project.montagne = 1
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_auto_20161003_2006'),
    ]

    operations = [
        migrations.RunPython(change_bool, reverse_func),
    ]
