# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_auto_20161003_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='littorale',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='montagne',
            field=models.BooleanField(),
        ),
    ]
