# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:29
from __future__ import unicode_literals

from django.db import migrations

def change_candidate(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.candidat_label == 'OUI':
            project.candidat_label = 1
        else:
            project.candidat_label = 0
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_auto_20161003_2028'),
    ]

    operations = [
        migrations.RunPython(change_candidate, reverse_func),
    ]
