# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_auto_20161003_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='candidat_label',
            field=models.BooleanField(),
        ),
    ]
