# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 21:01
from __future__ import unicode_literals

from django.db import migrations


def number_fields(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        project.superficieha = project.superficieha.replace(',', '.')
        if project.superficieha == '':
            project.superficieha = 0
        project.surface_nonbatie = project.surface_nonbatie.replace(',', '.')
        if project.surface_nonbatie == '':
            project.surface_nonbatie = 0
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_auto_20161003_2050'),
    ]

    operations = [
        migrations.RunPython(number_fields, reverse_func),
    ]
