# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_auto_20161003_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='superficieha',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='surface_nonbatie',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
