# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0038_auto_20161003_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='habitants',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='logements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_logementsm',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='superficieha',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='surface_nonbatie',
            field=models.FloatField(null=True),
        ),
    ]
