# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 15:47
from __future__ import unicode_literals

from django.db import migrations


def shon_empty(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.shon_equipementsm == '':
            project.shon_equipementsm = None
        if project.shon_commercesm == '':
            project.shon_commercesm = None
        if project.shon_bureauxm == '':
            project.shon_bureauxm = None
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_auto_20161004_1546'),
    ]

    operations = [
        migrations.RunPython(shon_empty, reverse_func),
    ]
