# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_auto_20161004_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='densite_brute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='densite_brute_logements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='densite_logements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
