# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 19:27
from __future__ import unicode_literals

from django.db import migrations


def densite_empty(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.densite_brute == '':
            project.densite_brute = None
        if project.densite_brute_logements == '':
            project.densite_brute_logements = None
        if project.densite_logements == '':
            project.densite_logements = None
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0043_auto_20161004_1927'),
    ]

    operations = [
        migrations.RunPython(densite_empty, reverse_func),
    ]
