# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 20:18
from __future__ import unicode_literals

from django.db import migrations


def onetoone(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    CommissionNationale2009 = apps.get_model("projects", "CommissionNationale2009")
    CommissionNationale2011 = apps.get_model("projects", "CommissionNationale2011")
    CommissionNationale2013 = apps.get_model("projects", "CommissionNationale2013")
    CommissionNationale2014 = apps.get_model("projects", "CommissionNationale2014")
    CommissionNationale2015 = apps.get_model("projects", "CommissionNationale2015")
    CommissionNationale2016 = apps.get_model("projects", "CommissionNationale2016")
    projects = Project.objects.all()
    for project in projects:
        if project.expertise_2009_e2009 != '' or project.avis_e2009 != '' or project.propositions_prix_e2009 != '' or project.etat_avancement_e2009 != '' or project.points_vigilance_e2009 != '':
            p2009 = CommissionNationale2009(project=project,
                        expertise_2009_e2009 = project.expertise_2009_e2009,
                        avis_e2009 = project.avis_e2009,
                        propositions_prix_e2009 = project.propositions_prix_e2009,
                        etat_avancement_e2009 = project.etat_avancement_e2009,
                        points_vigilance_e2009 = project.points_vigilance_e2009)
            p2009.save()

        if project.expert_interne_ei2011 != '' or project.avis_general_ei2011 != '' or project.propositions_prix_ei2011 != '' or project.demarche_processus_ei2011 != '' or project.cadre_vie_usage_ei2011 != '' or project.developpement_territorial_ei2011 != '' or project.ressources_climat_ei2011 != '' or project.approche_integree_ei2011 != '' or project.etat_avancement_ei2011 != '' or project.expert_externe_ee2011 != '' or project.avis_general_ee2011 != '' or project.propositions_prix_ee2011 != '' or project.demarche_processus_ee2011 != '' or project.cadre_vie_usage_ee2011 != '' or project.developpement_territorial_ee2011 != '' or project.ressources_climat_ee2011 != '' or project.approche_integree_ee2011 != '' or project.etat_avancement_ee2011 != '' or project.expert_local_el2011 != '' or project.synthese_avis_el2011 != '' or project.propositions_prix_el2011 != '' or project.alerte_el2011 != '':
            p2011 = CommissionNationale2011(project = project,
                        expert_interne_ei2011 = project.expert_interne_ei2011,
                        avis_general_ei2011 = project.avis_general_ei2011,
                        propositions_prix_ei2011 = project.propositions_prix_ei2011,
                        demarche_processus_ei2011 = project.demarche_processus_ei2011,
                        cadre_vie_usage_ei2011 = project.cadre_vie_usage_ei2011,
                        developpement_territorial_ei2011 = project.developpement_territorial_ei2011,
                        ressources_climat_ei2011 = project.ressources_climat_ei2011,
                        approche_integree_ei2011 = project.approche_integree_ei2011,
                        etat_avancement_ei2011 = project.etat_avancement_ei2011,
                        expert_externe_ee2011 = project.expert_externe_ee2011,
                        avis_general_ee2011 = project.avis_general_ee2011,
                        propositions_prix_ee2011 = project.propositions_prix_ee2011,
                        demarche_processus_ee2011 = project.demarche_processus_ee2011,
                        cadre_vie_usage_ee2011 = project.cadre_vie_usage_ee2011,
                        developpement_territorial_ee2011 = project.developpement_territorial_ee2011,
                        ressources_climat_ee2011 = project.ressources_climat_ee2011,
                        approche_integree_ee2011 = project.approche_integree_ee2011,
                        etat_avancement_ee2011 = project.etat_avancement_ee2011,
                        expert_local_el2011 = project.expert_local_el2011,
                        synthese_avis_el2011 = project.synthese_avis_el2011,
                        propositions_prix_el2011 = project.propositions_prix_el2011,
                        alerte_el2011 = project.alerte_el2011)
            p2011.save()

        if project.commission_nationale_cn2016 != '' or project.decision_cn2016 != '' or project.demarche_processus_cn2016 != '' or project.cadre_vie_usage_cn2016 != '' or project.developpement_territorial_cn2016 != '' or project.ressources_climat_cn2016 != '' or project.etat_avancement_cn2016 != '' or project.commission_regionale_cr2016 != '' or project.proposition_cr2016 != '' or project.demarche_processus_cr2016 != '' or project.cadre_vie_usage_cr2016 != '' or project.developpement_territorial_cr2016 != '' or project.ressources_climat_cr2016 != '' or project.etat_avancement_cr2016 != '' or project.avis_triple_expert_te2016 != '' or project.proposition_te2016 != '' or project.expert_interne_ei2016 != '' or project.avis_general_ei2016 != '' or project.expert_externe_ee2016 != '' or project.avis_general_ee2016 != '' or project.expert_territ_et2016 != '' or project.synthese_avis_et2016 != '' or project.synthese_avis_opportunite_dd2016 != '':

            cn2016 = CommissionNationale2016(project = project,
                commission_nationale_cn2016 = project.commission_nationale_cn2016,
                decision_cn2016 = project.decision_cn2016,
                demarche_processus_cn2016 = project.demarche_processus_cn2016,
                cadre_vie_usage_cn2016 = project.cadre_vie_usage_cn2016,
                developpement_territorial_cn2016 = project.developpement_territorial_cn2016,
                ressources_climat_cn2016 = project.ressources_climat_cn2016,
                etat_avancement_cn2016 = project.etat_avancement_cn2016,
                commission_regionale_cr2016 = project.commission_regionale_cr2016,
                proposition_cr2016 = project.proposition_cr2016,
                demarche_processus_cr2016 = project.demarche_processus_cr2016,
                cadre_vie_usage_cr2016 = project.cadre_vie_usage_cr2016,
                developpement_territorial_cr2016 = project.developpement_territorial_cr2016,
                ressources_climat_cr2016 = project.ressources_climat_cr2016,
                etat_avancement_cr2016 = project.etat_avancement_cr2016,
                avis_triple_expert_te2016 = project.avis_triple_expert_te2016,
                proposition_te2016 = project.proposition_te2016,
                expert_interne_ei2016 = project.expert_interne_ei2016,
                avis_general_ei2016 = project.avis_general_ei2016,
                expert_externe_ee2016 = project.expert_externe_ee2016,
                avis_general_ee2016 = project.avis_general_ee2016,
                expert_territ_et2016 = project.expert_territ_et2016,
                synthese_avis_et2016 = project.synthese_avis_et2016,
                synthese_avis_opportunite_dd2016 = project.synthese_avis_opportunite_dd2016)
            cn2016.save()

        if project.commission_nationale_cn2015 != '' or project.decision_cn2015 != '' or project.demarche_processus_cn2015 != '' or project.cadre_vie_usage_cn2015 != '' or project.developpement_territorial_cn2015 != '' or project.ressources_climat_cn2015 != '' or project.etat_avancement_cn2015 != '' or project.commission_regionale_cr2015 != '' or project.proposition_cr2015 != '' or project.demarche_processus_cr2015 != '' or project.cadre_vie_usage_cr2015 != '' or project.developpement_territorial_cr2015 != '' or project.ressources_climat_cr2015 != '' or project.etat_avancement_cr2015 != '' or project.avis_triple_expert_te2015 != '' or project.proposition_te2015 != '' or project.expert_interne_ei2015 != '' or project.avis_general_ei2015 != '' or project.expert_externe_ee2015 != '' or project.avis_general_ee2015 != '' or project.expert_territ_et2015 != '' or project.synthese_avis_et2015 != '' or project.synthese_avis_opportunite_dd2015 != '':

            cn2015 = CommissionNationale2015(project = project,
                commission_nationale_cn2015 = project.commission_nationale_cn2015,
                decision_cn2015 = project.decision_cn2015,
                demarche_processus_cn2015 = project.demarche_processus_cn2015,
                cadre_vie_usage_cn2015 = project.cadre_vie_usage_cn2015,
                developpement_territorial_cn2015 = project.developpement_territorial_cn2015,
                ressources_climat_cn2015 = project.ressources_climat_cn2015,
                etat_avancement_cn2015 = project.etat_avancement_cn2015,
                commission_regionale_cr2015 = project.commission_regionale_cr2015,
                proposition_cr2015 = project.proposition_cr2015,
                demarche_processus_cr2015 = project.demarche_processus_cr2015,
                cadre_vie_usage_cr2015 = project.cadre_vie_usage_cr2015,
                developpement_territorial_cr2015 = project.developpement_territorial_cr2015,
                ressources_climat_cr2015 = project.ressources_climat_cr2015,
                etat_avancement_cr2015 = project.etat_avancement_cr2015,
                avis_triple_expert_te2015 = project.avis_triple_expert_te2015,
                proposition_te2015 = project.proposition_te2015,
                expert_interne_ei2015 = project.expert_interne_ei2015,
                avis_general_ei2015 = project.avis_general_ei2015,
                expert_externe_ee2015 = project.expert_externe_ee2015,
                avis_general_ee2015 = project.avis_general_ee2015,
                expert_territ_et2015 = project.expert_territ_et2015,
                synthese_avis_et2015 = project.synthese_avis_et2015,
                synthese_avis_opportunite_dd2015 = project.synthese_avis_opportunite_dd2015)
            cn2015.save()


        if project.commission_nationale_cn2014 != '' or project.decision_cn2014 != '' or project.demarche_processus_cn2014 != '' or project.cadre_vie_usage_cn2014 != '' or project.developpement_territorial_cn2014 != '' or project.ressources_climat_cn2014 != '' or project.etat_avancement_cn2014 != '' or project.commission_regionale_cr2014 != '' or project.proposition_cr2014 != '' or project.demarche_processus_cr2014 != '' or project.cadre_vie_usage_cr2014 != '' or project.developpement_territorial_cr2014 != '' or project.ressources_climat_cr2014 != '' or project.etat_avancement_cr2014 != '' or project.avis_triple_expert_te2014 != '' or project.expert_interne_ei2014 != '' or project.avis_general_ei2014 != '' or project.expert_externe_ee2014 != '' or project.avis_general_ee2014 != '' or project.expert_territ_et2014 != '' or project.synthese_avis_et2014 != '' or project.synthese_avis_opportunite_dd2014 != '':

            cn2014 = CommissionNationale2014(project = project,
                commission_nationale_cn2014 = project.commission_nationale_cn2014,
                decision_cn2014 = project.decision_cn2014,
                demarche_processus_cn2014 = project.demarche_processus_cn2014,
                cadre_vie_usage_cn2014 = project.cadre_vie_usage_cn2014,
                developpement_territorial_cn2014 = project.developpement_territorial_cn2014,
                ressources_climat_cn2014 = project.ressources_climat_cn2014,
                etat_avancement_cn2014 = project.etat_avancement_cn2014,
                commission_regionale_cr2014 = project.commission_regionale_cr2014,
                proposition_cr2014 = project.proposition_cr2014,
                demarche_processus_cr2014 = project.demarche_processus_cr2014,
                cadre_vie_usage_cr2014 = project.cadre_vie_usage_cr2014,
                developpement_territorial_cr2014 = project.developpement_territorial_cr2014,
                ressources_climat_cr2014 = project.ressources_climat_cr2014,
                etat_avancement_cr2014 = project.etat_avancement_cr2014,
                avis_triple_expert_te2014 = project.avis_triple_expert_te2014,
                expert_interne_ei2014 = project.expert_interne_ei2014,
                avis_general_ei2014 = project.avis_general_ei2014,
                expert_externe_ee2014 = project.expert_externe_ee2014,
                avis_general_ee2014 = project.avis_general_ee2014,
                expert_territ_et2014 = project.expert_territ_et2014,
                synthese_avis_et2014 = project.synthese_avis_et2014,
                synthese_avis_opportunite_dd2014 = project.synthese_avis_opportunite_dd2014)
            cn2014.save()

        if project.demarche_processus_el2013 != '' or project.cadre_vie_usage_el2013 != '' or project.developpement_territorial_el2013 != '' or project.ressources_climat_el2013 != '' or project.synthese_avis_el2013 != '' or project.proposition_el2013 != '':

            cn2013 = CommissionNationale2013(project = project,
                demarche_processus_el2013 = project.demarche_processus_el2013,
                cadre_vie_usage_el2013 = project.cadre_vie_usage_el2013,
                developpement_territorial_el2013 = project.developpement_territorial_el2013,
                ressources_climat_el2013 = project.ressources_climat_el2013,
                synthese_avis_el2013 = project.synthese_avis_el2013,
                proposition_el2013 = project.proposition_el2013)
            cn2013.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_auto_20161004_2012'),
    ]

    operations = [
        migrations.RunPython(onetoone, reverse_func),
    ]
