# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 15:49
from __future__ import unicode_literals

from django.db import migrations


def logements_sociau(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.logements_sociau == '':
            project.logements_sociau = None
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0050_auto_20161005_1549'),
    ]

    operations = [
        migrations.RunPython(logements_sociau, reverse_func),
    ]
