# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_auto_20161005_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='laureat',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='participation_2009',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='participation_2011',
            field=models.BooleanField(),
        ),
    ]
