# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:16
from __future__ import unicode_literals

from django.db import migrations


def annee(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.annee_candidature == '':
            project.annee_candidature = None
        if project.annee_label == '':
            project.annee_label = None
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_auto_20161005_1616'),
    ]

    operations = [
        migrations.RunPython(annee, reverse_func),
    ]
