# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_auto_20161005_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='annee_candidature',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='annee_label',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
