# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-05 16:29
from __future__ import unicode_literals

from django.db import migrations


def annee(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    projects = Project.objects.all()
    for project in projects:
        if project.engagement == '':
            project.engagement = None
        if project.creation == '':
            project.creation = None
        if project.realisation == '':
            project.realisation = None
        if project.autorisation == '':
            project.autorisation = None
        if project.permis == '':
            project.permis = None
        if project.debut == '':
            project.debut = None
        if project.livraison == '':
            project.livraison = None
        if project.achevement == '':
            project.achevement = None
        if project.complementaire == '':
            project.complementaire = None
        project.save()


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_auto_20161005_1629'),
    ]

    operations = [
        migrations.RunPython(annee, reverse_func),
    ]
