# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-07 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0061_auto_20161005_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='editors',
            field=models.ManyToManyField(related_name='editors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
