# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20161008_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mise_a_jour',
            field=models.DateField(auto_now_add=True),
        ),
    ]
