# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_auto_20161009_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='candidat_label',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='habitants',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='label_ecoquartier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.LabelEcoQuartier', verbose_name='Label \xc9coQuartier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='laureat',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='littorale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='logements',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='montagne',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='nomine',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='participation_2009',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='participation_2011',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_logementsm',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.TypeOperation', verbose_name="Type d'op\xe9ration"),
        ),
        migrations.AlterField(
            model_name='project',
            name='zonage_insee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.ZonageINSEE', verbose_name='Zonage INSEE'),
        ),
    ]
