# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_auto_20161015_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_operations',
            field=models.ManyToManyField(to='projects.TypeOperation', verbose_name="Type d'op\xe9rations"),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_operation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_type_operation', to='projects.TypeOperation', verbose_name="Type d'op\xe9ration"),
        ),
    ]
