# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 13:03
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        project.type_operations.add(project.type_operation)


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0067_auto_20161015_1302'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
