# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_auto_20161015_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='type_operation',
        ),
    ]
