# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 14:58
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    LabelEcoQuartier = apps.get_model("projects", "LabelEcoQuartier")
    l, created = LabelEcoQuartier.objects.get_or_create(label="charte")


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_remove_project_type_operation'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
