# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 15:02
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    ps = Project.objects.all()
    for p in ps:
        if p.label_ecoquartier and p.label_ecoquartier.id == 1:
            p.label_ecoquartier = None
            p.save()


def backward(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0070_auto_20161015_1458'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
