# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-15 15:05
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    LabelEcoQuartier = apps.get_model("projects", "LabelEcoQuartier")
    l = LabelEcoQuartier.objects.get(id=1).delete()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_auto_20161015_1502'),
    ]

    operations = [
    	migrations.RunPython(forward, backward),
    ]
