# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20161015_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='label_ecoquartier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.LabelEcoQuartier', verbose_name="\xc9tat d'avancement"),
        ),
    ]
