# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 08:51
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Tag = apps.get_model("projects", "Tag")
    eau, created = Tag.objects.get_or_create(label='eau')
    dechets, created = Tag.objects.get_or_create(label='dechets')
    biodiversite, created = Tag.objects.get_or_create(label='biodiversite')
    mobilite, created = Tag.objects.get_or_create(label='mobilite')
    sobriete_energetique_et_energie_renouvelable, created = Tag.objects.get_or_create(label='sobriete_energetique_et_energie_renouvelable')
    densite_et_formes_urbaines, created = Tag.objects.get_or_create(label='densite_et_formes_urbaines')
    ecoconstruction, created = Tag.objects.get_or_create(label='ecoconstruction')
    demarches_et_processus, created = Tag.objects.get_or_create(label='demarches_et_processus')
    cadre_de_vie_et_usages, created = Tag.objects.get_or_create(label='cadre_de_vie_et_usages')

    projects = Project.objects.all()
    for project in projects:
        if project.eau != '':
            project.tags.add(eau)
        if project.dechets != '':
            project.tags.add(dechets)
        if project.biodiversite != '':
            project.tags.add(biodiversite)
        if project.mobilite != '':
            project.tags.add(mobilite)
        if project.sobriete_energetique_et_energie_renouvelable != '':
            project.tags.add(sobriete_energetique_et_energie_renouvelable)
        if project.densite_et_formes_urbaines != '':
            project.tags.add(densite_et_formes_urbaines)
        if project.ecoconstruction != '':
            project.tags.add(ecoconstruction)
        if project.demarches_et_processus != '':
            project.tags.add(demarches_et_processus)
        if project.cadre_de_vie_et_usages != '':
            project.tags.add(cadre_de_vie_et_usages)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_auto_20161016_0851'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
