# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_auto_20161016_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charte',
            field=models.FileField(blank=True, null=True, upload_to='charte/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='project',
            name='charte_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
