# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20161017_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='communes',
            field=models.ManyToManyField(related_name='other_communes', to='projects.Commune'),
        ),
    ]
