# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_project_communes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demarche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='demarches',
            field=models.ManyToManyField(to='projects.Demarche'),
        ),
    ]
