# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_auto_20161018_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager_firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pr\xe9nom du chef de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du chef de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail du chef de projet'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager_structure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Structure du chef de projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='charte',
            field=models.FileField(blank=True, null=True, upload_to='charte/%Y/%m/%d/', verbose_name='Charte \xc9coQuartier'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commune',
            field=models.ForeignKey(help_text="Sur quelle commune est situ\xe9 l'\xc9coQuartier", null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Commune', verbose_name='Commune principale'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demarches',
            field=models.ManyToManyField(to='projects.Demarche', verbose_name="Engagement dans d'autres d\xe9marches de d\xe9veloppement durable"),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='10 lignes maximum', verbose_name='Description du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nom',
            field=models.CharField(max_length=255, verbose_name="Nom de l'\xc9coQuartier"),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(to='projects.Tag', verbose_name='Points forts du projet'),
        ),
    ]
