# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_auto_20161020_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='vocations',
            field=models.ManyToManyField(to='projects.Vocation'),
        ),
        migrations.AlterField(
            model_name='project',
            name='vocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_vocation', to='projects.Vocation'),
        ),
    ]
