# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:29
from __future__ import unicode_literals

from django.db import migrations


def forward(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        project.vocations.add(project.vocation)


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_auto_20161020_1929'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
