# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0084_remove_project_vocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeoperation',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocation',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
