# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0085_auto_20161020_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='departement',
            name='code_insee',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='region',
            name='code_insee',
            field=models.CharField(default='', max_length=255),
        ),
    ]
