# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 09:24
from __future__ import unicode_literals
import re

from django.db import migrations


def forward(apps, schema_editor):
    p = re.compile("\((.+)\)")
    Departement = apps.get_model("projects", "Departement")
    for departement in Departement.objects.all():
        label = departement.label
        insee = re.match('.+\((.+)\)', label).group(1)
        departement.code_insee = insee
        departement.save()


def backward(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0086_auto_20161102_0916'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
