# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0090_document_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='engagement',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
