# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0092_auto_20161103_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logements_sociaux_detail',
            field=models.TextField(default='', verbose_name='Logements sociaux d\xe9tail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.CharField(choices=[('01', 'A r\xe9aliser'), ('02', 'En cours'), ('03', 'R\xe9alis\xe9')], default='01', max_length=2),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('ph', 'Photo'), ('pl', 'Plan'), ('et', 'Etude, diagnostic'), ('pa', 'Planification')], default='fo', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='achevement',
            field=models.IntegerField(blank=True, help_text='Anne\u0301e d\u2019ache\u0300vement de l\u2019ope\u0301ration', null=True, verbose_name="Date d'ach\xe8vement de l'op\xe9ration"),
        ),
        migrations.AlterField(
            model_name='project',
            name='autorisation',
            field=models.IntegerField(blank=True, help_text='Anne\u0301e d\u2019autorisation d\u2019ame\u0301nager (si permis d\u2019ame\u0301nager)', null=True, verbose_name="Date d'autorisation d'am\xe9nager"),
        ),
        migrations.AlterField(
            model_name='project',
            name='bureaux_activites',
            field=models.TextField(help_text="Pr\xe9ciser le type d'activit\xe9s pr\xe9vues dans l'op\xe9ration", verbose_name='D\xe9tail bureaux et activit\xe9s'),
        ),
        migrations.AlterField(
            model_name='project',
            name='commerces_services',
            field=models.TextField(help_text="Pr\xe9ciser le type de commerces et services programm\xe9s dans l'op\xe9ration", verbose_name='D\xe9tail commerces et services'),
        ),
        migrations.AlterField(
            model_name='project',
            name='complementaire',
            field=models.IntegerField(blank=True, help_text='Autre date importante non cit\xe9e ci-dessus', null=True, verbose_name='Date compl\xe9mentaire'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contexte_site',
            field=models.TextField(help_text='\n<p>\nLa collectivite\u0301 fait-elle partie d\u2019une intercommunalite\u0301 ? Si oui,de quel type d\u2019EPCI s\u2019agit-il ? Quel est le nom de cet EPCI ?\n<br>\nQuels sont les e\u0301le\u0301ments de cadrage et de plani cation valables sur le territoire de la collectivite\u0301 ?\n<br>\nLe pe\u0301rime\u0300tre ope\u0301rationnel de l\u2019EcoQuartier est-il soumis a\u0300 des orientations d\u2019ame\u0301nagement ?\n<br>\nSi oui, pre\u0301cisez lesquelles.\n<br>\nLe site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux en termes de patrimoine : pe\u0301rime\u0300tre de protection autour des monuments historiques ? Plan de Sauvegarde et de Mise en Valeur (PSMV)? Zone de protection du patrimoine architectural et paysager (ZPPAUP) / Aire de valorisation de l\u2019Architecture et du Patrimoine (AVAP) ? Autres : pre\u0301cisez lesquelles.\n<br>\nLe site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux naturels et paysagers : Zone naturelle d\u2019inte\u0301re\u0302t Ecologique, Faunistique et Floristiques (ZNIEFF) ? NATURA 2000 ? Espace Boise\u0301 Classe\u0301 (EBC) ? Espace Naturel Sensible (ENS) ? Autres : pre\u0301cisez lesquelles.\n<br>\nLe site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre faisant l\u2019objet de conventions particulie\u0300res : Pe\u0301rime\u0300tre Agence Nationale pour la Re\u0301novation Urbaine (ANRU) ? Convention Programme National de Requali cation des Quartiers Anciens De\u0301grade\u0301s (PNRQAD) ? Ope\u0301ration Programme\u0301e d\u2019Ame\u0301lioration de l\u2019Habitat (OPAH) ? Zone Franche Urbaine (ZFU) ? Autres : pre\u0301cisez lesquelles ? Le site de l\u2019EcoQuartier est-il soumis a\u0300 des servitudes particulie\u0300res ? Si oui,pre\u0301cisez lesquelles.\n</p>\n', verbose_name='Contexte du site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='creation',
            field=models.IntegerField(blank=True, help_text='L\u2019anne\u0301e de cre\u0301ation de la ZAC (si ZAC)', null=True, verbose_name='Date de cr\xe9ation de la ZAC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='debut',
            field=models.IntegerField(blank=True, help_text='anne\u0301e du de\u0301but des travaux', null=True, verbose_name='Date du d\xe9but des travaux'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement',
            field=models.IntegerField(blank=True, help_text='L\u2019anne\u0301e d\u2019engagement de l\u2019ope\u0301ration : anne\u0301e de la premie\u0300re de\u0301libe\u0301ration concernant l\u2019ope\u0301ration', null=True, verbose_name="Date d'engagement de l'op\xe9ration"),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement_1',
            field=models.TextField(help_text='\n<div>\nLES DONNE\u0301ES QUALITATIVES\nDE\u0301CRIRE VOTRE PROJET\n\n<h6>NOTION 1 : DIAGNOSTIC STRATE\u0301GIQUE</h6>\n\n<ol>\n<li>Quels diagnostics ont e\u0301te\u0301 re\u0301alise\u0301s,et a\u0300 quelles e\u0301chelles ? Quels sont les champs couverts (sociaux,urbains,e\u0301conomiques et environnementaux) ? Quels sont les enjeux identi e\u0301s pour le projet ?</li>\n<li>Comment les diagnostics ont-ils e\u0301te\u0301 mobilise\u0301s pour de\u0301 nir le projet,notamment en prenant en compte la comple\u0301mentarite\u0301 avec les caracte\u0301ristiques des territoires voisins,les ressources locales,les attentes des habitants,usagers et acteurs socio- e\u0301conomiques ?</li>\n</ol>\n\n<h6>NOTION 2 : PROGRAMMATION</h6>\n\n<ol>\n<li>Comment la programmation inte\u0300gre-t-elle les enjeux et les besoins des habitants, des usagers et des acteurs socio- e\u0301conomiques identi e\u0301s dans les diagnostics, dans un souci d\u2019e\u0301quite\u0301 ?</li>\n<li>En quoi la programmation est-elle en ade\u0301quation avec le contexte local ? Exemples : ade\u0301quation de la programmation des logements avec les revenus des me\u0301nages et les capacite\u0301s des acteurs e\u0301conomiques et de la collectivite\u0301, de la programmation des e\u0301quipements publics avec la population vise\u0301e et l\u2019e\u0301tat des e\u0301quipements existants, de la programmation commerciale avec les besoins et l\u2019offre existante....</li>\n<li>Quelles sont les possibilite\u0301s d\u2019ajustement de la programmation en fonction de l\u2019e\u0301volution du contexte e\u0301conomique, politique,re\u0301glementaire,social ou climatique ?</li>\n</ol>\n\n</div>\n'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement_9',
            field=models.TextField(help_text='\n<div>\nLES DONNE\u0301ES QUALITATIVES\nDE\u0301CRIRE VOTRE PROJET\n</div>\n<h6>NOTION 1 : INSERTION URBAINE ET PAYSAGE\u0300RE</h6>\n\n<ol>\n<li>Comment le projet s\u2019articule-t-il a\u0300 son environnement urbain et naturel ?\nExemples : perspectives et points de vue, trame viaire, articulation avec les quartiers mitoyens,...</li>\n<li>Comment le projet prend-il en compte et exploite-t-il les e\u0301le\u0301ments paysagers pre\u0301sents sur le site ?</li>\n</ol>\n<h6>NOTION 2 : QUALITE\u0301 URBAINE ET ESPACES PUBLICS</h6>\n\n<ol>\n<li>Comment la composition et les formes urbaines participent-elles a\u0300 la cre\u0301ation d\u2019un cadre de vie agre\u0301able?\nExemples : maillage, structuration</li>\n<li>Quelle importance est accorde\u0301e aux espaces publics et quels ame\u0301nagements favorisant la qualite\u0301 de vie sont propose\u0301s dans le projet ?\nExemples : ope\u0301rations d\u2019espaces publics particulie\u0300res,inte\u0301gration de la multifonctionnalite\u0301 ...</li>\n<li>Comment la nature en ville participe-t-elle a\u0300 la qualite\u0301 du cadre de vie ?</li>\n</ol>\n\n<h6>NOTION 3 : QUALITE\u0301 ET CRE\u0301ATIVITE\u0301 ARCHITECTURALE</h6>\n\n<ol>\n<li>Comment les i\u0302lots et formes ba\u0302ties participent-ils a\u0300 une qualite\u0301 architecturale d\u2019ensemble du projet ?</li>\n<li>De quelle manie\u0300re favorisez-vous la cre\u0301ation et la qualite\u0301 architecturales dans les projets ?</li>\n</ol>\n\nExemples : projets architecturaux spe\u0301cifiques, consultation d\u2019e\u0301quipes mixtes d\u2019architectes-promoteurs-urbanistes, concours d\u2019ide\u0301es,...\n'),
        ),
        migrations.AlterField(
            model_name='project',
            name='equipements_publics',
            field=models.TextField(help_text='Pr\xe9cisions sur les \xe9quipements publics consid\xe9r\xe9s', verbose_name='D\xe9tail \xe9quipements publics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='habitants',
            field=models.IntegerField(default=0, verbose_name="Nombre d'habitants pr\xe9vus"),
        ),
        migrations.AlterField(
            model_name='project',
            name='livraison',
            field=models.IntegerField(blank=True, help_text='Ann\xe9e de livraison des premiers b\xe2timents', null=True, verbose_name='Date de livraison des premiers b\xe2timents'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logements',
            field=models.IntegerField(default=0, help_text='\n<p>\nQuel est le nombre de logements dans l\u2019EcoQuartier ?\n<br>\nPre\u0301ciser le nombre total de logements pre\u0301vus a\u0300 terme dans l\u2019ope\u0301ration (y compris logements re\u0301habilite\u0301s ou re\u0301nove\u0301s, a\u0300 pre\u0301ciser dans ce cas dans le de\u0301tail de l\u2019ope\u0301ration)\n</p>\n', verbose_name='Nombre de logements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='logements_sociau',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nombre de logements sociaux'),
        ),
        migrations.AlterField(
            model_name='project',
            name='opacrations_marquantes',
            field=models.TextField(help_text='<i>Si  au  sein  de  l\u2019op\xe9ration  d\u2019am\xe9nagement,  une  ou  plusieurs  constructions  ou  espaces  publics  majeurs  m\xe9ritent  d\u2019\xeatre  remarqu\xe9es,  vous  pouvez  nous  indiquer  ici  tous  les  \xe9l\xe9ments  n\xe9cessaires  (nom  du  b\xe2timent  ou  de  l\u2019espace  public,  fonction,  ma\xeetrise  d\u2019ouvrage  et  ma\xeetrise  d\u2019\u0153uvre,  particularit\xe9s  de  l\u2019op\xe9ration, autres \xe9l\xe9ments ou photographies en votre possession...)</i>', verbose_name='Op\xe9rations marquantes du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='permis',
            field=models.IntegerField(blank=True, help_text='anne\u0301e du permis de construire (si ope\u0301ration se limite a\u0300 un permis ou un permis groupe\u0301)', null=True, verbose_name='Date du permis de construire'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager_firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pr\xe9nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager_lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager_structure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisme de rattachement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='realisation',
            field=models.IntegerField(blank=True, help_text='Anne\u0301e de re\u0301alisation de la ZAC (si ZAC)', null=True, verbose_name='Date de r\xe9alisation de la ZAC'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_bureauxm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Surface de plancher bureaux et activit\xe9s'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_commercesm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Surface de plancher des commerces et services'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_equipementsm',
            field=models.IntegerField(blank=True, null=True, verbose_name='Surface \xe9quipements publics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='shon_logementsm',
            field=models.IntegerField(default=0, help_text='Surface hors \u0153uvre net des logements', verbose_name='SHON logement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.TextField(help_text='Pre\u0301ciser les caracte\u0301ristiques initiales du site : par exemple, terrains agricoles, site militaire, friches industrielles, quartier d\u2019habitat social...', verbose_name='Caract\xe9ristiques initiales du site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='superficieha',
            field=models.FloatField(help_text="Quelle est la superficie de l'EcoQuartier ? (ha)", null=True, verbose_name="Superficie de l'op\xe9ration"),
        ),
        migrations.AlterField(
            model_name='project',
            name='surface_nonbatie',
            field=models.FloatField(help_text='Toute surface non ba\u0302tie appartenant au domaine public, notamment voirie, espaces verts, espaces publics', null=True, verbose_name='Surface non ba\u0302tie publique'),
        ),
    ]
