# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-07 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0093_auto_20161107_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demarche',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='typeoperation',
            options={'ordering': ['label']},
        ),
        migrations.AlterModelOptions(
            name='vocation',
            options={'ordering': ['label']},
        ),
        migrations.AddField(
            model_name='tag',
            name='hide',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='action',
            name='name',
            field=models.CharField(max_length=255, verbose_name="Nom de l'action"),
        ),
        migrations.AlterField(
            model_name='action',
            name='state',
            field=models.CharField(choices=[('01', 'A r\xe9aliser'), ('02', 'En cours'), ('03', 'R\xe9alis\xe9')], default='01', max_length=2, verbose_name="Etat de l'action"),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d', verbose_name='Fichier'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
    ]
