# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-08 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0095_auto_20161108_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zonageinsee',
            options={'ordering': ['label']},
        ),
    ]
