# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0096_auto_20161108_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_developer_firstname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pr\xe9nom'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_developer_lastname',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_developer_mail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Mail'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_developer_structure',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Organisme de rattachement'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contexte_site',
            field=models.TextField(help_text='\n<ul>\n<li>La collectivite\u0301 fait-elle partie d\u2019une intercommunalite\u0301 ? Si oui, de quel type d\u2019EPCI s\u2019agit-il ? Quel est le nom de cet EPCI ?</li>\n\n<li>Quels sont les e\u0301le\u0301ments de cadrage et de plani cation valables sur le territoire de la collectivite\u0301 ?</li>\n\n<li>Le pe\u0301rime\u0300tre ope\u0301rationnel de l\u2019EcoQuartier est-il soumis a\u0300 des orientations d\u2019ame\u0301nagement ? Si oui, pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux en termes de patrimoine : pe\u0301rime\u0300tre de protection autour des monuments historiques ? Plan de Sauvegarde et de Mise en Valeur (PSMV)? Zone de protection du patrimoine architectural et paysager (ZPPAUP) / Aire de valorisation de l\u2019Architecture et du Patrimoine (AVAP) ? Autres : pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux naturels et paysagers : Zone naturelle d\u2019inte\u0301re\u0302t Ecologique, Faunistique et Floristiques (ZNIEFF) ? NATURA 2000 ? Espace Boise\u0301 Classe\u0301 (EBC) ? Espace Naturel Sensible (ENS) ? Autres : pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre faisant l\u2019objet de conventions particulie\u0300res : Pe\u0301rime\u0300tre Agence Nationale pour la Re\u0301novation Urbaine (ANRU) ? Convention Programme National de Requali cation des Quartiers Anciens De\u0301grade\u0301s (PNRQAD) ? Ope\u0301ration Programme\u0301e d\u2019Ame\u0301lioration de l\u2019Habitat (OPAH) ? Zone Franche Urbaine (ZFU) ? Autres : pre\u0301cisez lesquelles ? Le site de l\u2019EcoQuartier est-il soumis a\u0300 des servitudes particulie\u0300res ? Si oui, pre\u0301cisez lesquelles.</li>\n</ul>\n', verbose_name='Contexte du site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement_1',
            field=models.TextField(help_text='\n<div>\n<h5>Les donn\xe9es qualitatives / D\xe9crire votre projet</h5>\n\n<h6>NOTION 1 : DIAGNOSTIC STRATE\u0301GIQUE</h6>\n\n<ol>\n<li>Quels diagnostics ont e\u0301te\u0301 re\u0301alise\u0301s,et a\u0300 quelles e\u0301chelles ? Quels sont les champs couverts (sociaux,urbains,e\u0301conomiques et environnementaux) ? Quels sont les enjeux identi e\u0301s pour le projet ?</li>\n<li>Comment les diagnostics ont-ils e\u0301te\u0301 mobilise\u0301s pour de\u0301 nir le projet,notamment en prenant en compte la comple\u0301mentarite\u0301 avec les caracte\u0301ristiques des territoires voisins,les ressources locales,les attentes des habitants,usagers et acteurs socio- e\u0301conomiques ?</li>\n</ol>\n\n<h6>NOTION 2 : PROGRAMMATION</h6>\n\n<ol>\n<li>Comment la programmation inte\u0300gre-t-elle les enjeux et les besoins des habitants, des usagers et des acteurs socio- e\u0301conomiques identi e\u0301s dans les diagnostics, dans un souci d\u2019e\u0301quite\u0301 ?</li>\n<li>En quoi la programmation est-elle en ade\u0301quation avec le contexte local ? Exemples : ade\u0301quation de la programmation des logements avec les revenus des me\u0301nages et les capacite\u0301s des acteurs e\u0301conomiques et de la collectivite\u0301, de la programmation des e\u0301quipements publics avec la population vise\u0301e et l\u2019e\u0301tat des e\u0301quipements existants, de la programmation commerciale avec les besoins et l\u2019offre existante....</li>\n<li>Quelles sont les possibilite\u0301s d\u2019ajustement de la programmation en fonction de l\u2019e\u0301volution du contexte e\u0301conomique, politique,re\u0301glementaire,social ou climatique ?</li>\n</ol>\n\n</div>\n'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement_9',
            field=models.TextField(help_text='\n<div>\n<h5>Les donn\xe9es qualitatives / D\xe9crire votre projet</h5>\n<h6>NOTION 1 : INSERTION URBAINE ET PAYSAGE\u0300RE</h6>\n\n<ol>\n<li>Comment le projet s\u2019articule-t-il a\u0300 son environnement urbain et naturel ?\nExemples : perspectives et points de vue, trame viaire, articulation avec les quartiers mitoyens,...</li>\n<li>Comment le projet prend-il en compte et exploite-t-il les e\u0301le\u0301ments paysagers pre\u0301sents sur le site ?</li>\n</ol>\n<h6>NOTION 2 : QUALITE\u0301 URBAINE ET ESPACES PUBLICS</h6>\n\n<ol>\n<li>Comment la composition et les formes urbaines participent-elles a\u0300 la cre\u0301ation d\u2019un cadre de vie agre\u0301able?\nExemples : maillage, structuration</li>\n<li>Quelle importance est accorde\u0301e aux espaces publics et quels ame\u0301nagements favorisant la qualite\u0301 de vie sont propose\u0301s dans le projet ?\nExemples : ope\u0301rations d\u2019espaces publics particulie\u0300res,inte\u0301gration de la multifonctionnalite\u0301 ...</li>\n<li>Comment la nature en ville participe-t-elle a\u0300 la qualite\u0301 du cadre de vie ?</li>\n</ol>\n\n<h6>NOTION 3 : QUALITE\u0301 ET CRE\u0301ATIVITE\u0301 ARCHITECTURALE</h6>\n\n<ol>\n<li>Comment les i\u0302lots et formes ba\u0302ties participent-ils a\u0300 une qualite\u0301 architecturale d\u2019ensemble du projet ?</li>\n<li>De quelle manie\u0300re favorisez-vous la cre\u0301ation et la qualite\u0301 architecturales dans les projets ?</li>\n</ol>\n<p>\nExemples : projets architecturaux spe\u0301cifiques, consultation d\u2019e\u0301quipes mixtes d\u2019architectes-promoteurs-urbanistes, concours d\u2019ide\u0301es,...\n</p>\n</div>\n'),
        ),
    ]
