# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0097_auto_20161201_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='plusieurs_tranches',
            field=models.BooleanField(default=False, verbose_name="L'op\xe9ration comporte plusieurs tranches"),
        ),
    ]
