# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0098_project_plusieurs_tranches'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demarches_autres',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='type_operations',
            field=models.ManyToManyField(help_text='Plusieurs choix possibles', to='projects.TypeOperation', verbose_name="Type d'op\xe9rations (plusieurs choix possibles)"),
        ),
    ]
