# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0099_auto_20161201_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaitreOeuvre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, verbose_name='Nom')),
                ('mail', models.CharField(max_length=255, verbose_name='Mail')),
                ('fonction', models.CharField(choices=[('AR', 'Architecte'), ('UR', 'Urbaniste'), ('PA', 'Paysagiste'), ('EC', 'Ecologue'), ('BE', 'BE')], max_length=2)),
                ('competence', models.CharField(choices=[('PO', 'Am\xe9nagement en site pollu\xe9'), ('PR', 'Am\xe9nagement en site prot\xe9g\xe9')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PartenaireDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=64)),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Partenaire')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='maitrise_ouvrage_nom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='maitrise_ouvrage_structure',
            field=models.CharField(blank=True, choices=[('RC', 'r\xe9gie communale'), ('SM', 'SEM'), ('SP', 'SPLA'), ('AP', 'Am\xe9nageur priv\xe9')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_detaille',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_masse_1_1000',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_masse_1_500',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='project',
            name='plan_situation_1_5000',
            field=models.FileField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contexte_site',
            field=models.TextField(help_text='\n<p>Pr\xe9cisez en 10 lignes maximum : </p>\n<ul>\n<li>La collectivite\u0301 fait-elle partie d\u2019une intercommunalite\u0301 ? Si oui, de quel type d\u2019EPCI s\u2019agit-il ? Quel est le nom de cet EPCI ?</li>\n\n<li>Quels sont les e\u0301le\u0301ments de cadrage et de plani cation valables sur le territoire de la collectivite\u0301 ?</li>\n\n<li>Le pe\u0301rime\u0300tre ope\u0301rationnel de l\u2019EcoQuartier est-il soumis a\u0300 des orientations d\u2019ame\u0301nagement ? Si oui, pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux en termes de patrimoine : pe\u0301rime\u0300tre de protection autour des monuments historiques ? Plan de Sauvegarde et de Mise en Valeur (PSMV)? Zone de protection du patrimoine architectural et paysager (ZPPAUP) / Aire de valorisation de l\u2019Architecture et du Patrimoine (AVAP) ? Autres : pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre de protection ou dans une zone a\u0300 enjeux naturels et paysagers : Zone naturelle d\u2019inte\u0301re\u0302t Ecologique, Faunistique et Floristiques (ZNIEFF) ? NATURA 2000 ? Espace Boise\u0301 Classe\u0301 (EBC) ? Espace Naturel Sensible (ENS) ? Autres : pre\u0301cisez lesquelles.</li>\n\n<li>Le site de l\u2019EcoQuartier est-il inclus dans un pe\u0301rime\u0300tre faisant l\u2019objet de conventions particulie\u0300res : Pe\u0301rime\u0300tre Agence Nationale pour la Re\u0301novation Urbaine (ANRU) ? Convention Programme National de Requali cation des Quartiers Anciens De\u0301grade\u0301s (PNRQAD) ? Ope\u0301ration Programme\u0301e d\u2019Ame\u0301lioration de l\u2019Habitat (OPAH) ? Zone Franche Urbaine (ZFU) ? Autres : pre\u0301cisez lesquelles ? Le site de l\u2019EcoQuartier est-il soumis a\u0300 des servitudes particulie\u0300res ? Si oui, pre\u0301cisez lesquelles.</li>\n</ul>\n', verbose_name='Contexte du site'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demarches_autres',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Autres d\xe9marches'),
        ),
        migrations.AlterField(
            model_name='project',
            name='engagement_1',
            field=models.TextField(help_text='\n<div>\n<h5>Les donn\xe9es qualitatives / D\xe9crire votre projet</h5>\n\n<h6>NOTION 1 : DIAGNOSTIC STRATE\u0301GIQUE</h6>\n\n<ol>\n<li>Quels diagnostics ont e\u0301te\u0301 re\u0301alise\u0301s,et a\u0300 quelles e\u0301chelles ? Quels sont les champs couverts (sociaux,urbains,e\u0301conomiques et environnementaux) ? Quels sont les enjeux identi e\u0301s pour le projet ?</li>\n<li>Comment les diagnostics ont-ils e\u0301te\u0301 mobilise\u0301s pour de\u0301 nir le projet,notamment en prenant en compte la comple\u0301mentarite\u0301 avec les caracte\u0301ristiques des territoires voisins,les ressources locales,les attentes des habitants,usagers et acteurs socio- e\u0301conomiques ?</li>\n</ol>\n\n<h6>NOTION 2 : PROGRAMMATION</h6>\n\n<ol>\n<li>Comment la programmation inte\u0300gre-t-elle les enjeux et les besoins des habitants, des usagers et des acteurs socio- e\u0301conomiques identi e\u0301s dans les diagnostics, dans un souci d\u2019e\u0301quite\u0301 ?</li>\n<li>En quoi la programmation est-elle en ade\u0301quation avec le contexte local ? Exemples : ade\u0301quation de la programmation des logements avec les revenus des me\u0301nages et les capacite\u0301s des acteurs e\u0301conomiques et de la collectivite\u0301, de la programmation des e\u0301quipements publics avec la population vise\u0301e et l\u2019e\u0301tat des e\u0301quipements existants, de la programmation commerciale avec les besoins et l\u2019offre existante....</li>\n<li>Quelles sont les possibilite\u0301s d\u2019ajustement de la programmation en fonction de l\u2019e\u0301volution du contexte e\u0301conomique, politique,re\u0301glementaire,social ou climatique ?</li>\n</ol>\n\n</div>\n', verbose_name='Engagement 1 (2000 signes maximum sans compter les espaces)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='site',
            field=models.TextField(help_text='Pre\u0301ciser en 5 lignes maximum les caracte\u0301ristiques initiales du site : par exemple, terrains agricoles, site militaire, friches industrielles, quartier d\u2019habitat social...', verbose_name='Caract\xe9ristiques initiales du site'),
        ),
        migrations.AddField(
            model_name='partenairedetail',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='partenaires',
            field=models.ManyToManyField(through='projects.PartenaireDetail', to='projects.Partenaire'),
        ),
    ]
