# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-01 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0100_auto_20161201_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='maitreoeuvre',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.Project'),
        ),
    ]
